import React, { useEffect, useRef } from "react";
import mermaid from "mermaid";
import { Download, ZoomIn, ZoomOut } from "lucide-react";

mermaid.initialize({
  startOnLoad: true,
  theme: "dark",
  securityLevel: "loose",
  fontFamily: "Inter",
});

export default function DiagramView({ code }: { code: string }) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (ref.current && code) {
      // Clean up code - sometimes Gemini adds backticks
      const cleanCode = code.replace(/```mermaid/g, "").replace(/```/g, "").trim();
      
      ref.current.innerHTML = `<div class="mermaid">${cleanCode}</div>`;
      mermaid.contentLoaded();
    }
  }, [code]);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex gap-2">
          <button className="p-2 glass rounded-lg text-white/40 hover:text-white"><ZoomIn size={16} /></button>
          <button className="p-2 glass rounded-lg text-white/40 hover:text-white"><ZoomOut size={16} /></button>
        </div>
        <button className="px-4 py-2 glass rounded-lg text-xs font-bold flex items-center gap-2">
          <Download size={14} /> Download SVG
        </button>
      </div>

      <div className="glass-card p-8 min-h-[300px] flex items-center justify-center overflow-auto bg-white/5">
        <div ref={ref} className="w-full" />
      </div>

      <p className="text-[10px] text-white/30 text-center italic">
        Diagram generated by AI based on your study material.
      </p>
    </div>
  );
}
